spring:
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/fastcampus_pay?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: mysqluser
        password: mysqlpw
        driver-class-name: com.mysql.cj.jdbc.Driver

  batch: #TODO
    jdbc:
      initialize-schema: always
    job.name: ${job.name:NONE}
    chunk-size: 1000


  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  jwtSecretKey: 2ifamoxz94kcpwigfi9spcadcfawasadff324rfsdfsdfsfsd
  expirationTime: 3600000
